name: Build Lisp packages

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
     matrix:
       lisp: [ abcl, ecl, ccl, clasp, clisp, sbcl ]

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v25

      - name: build
        run: nix run --no-write-lock-file nixpkgs#sbcl -- --script test-lisp.lisp ${{ matrix.lisp }}
